# Generated by Django 2.0.2 on 2018-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180301_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
