# Generated by Django 2.0.2 on 2018-03-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180301_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='_class',
            new_name='class_name',
        ),
    ]
