# Generated by Django 2.0.2 on 2018-03-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180302_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value', models.IntegerField()),
                ('excel_min_value', models.IntegerField(default=8)),
                ('good_min_value', models.IntegerField(default=6)),
                ('satis_min_value', models.IntegerField(default=4)),
                ('subject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.IntegerField(),
        ),
    ]
