# Generated by Django 2.0.2 on 2018-03-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180306_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectconfig',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.SubjectConfig'),
        ),
        migrations.AlterField(
            model_name='subjectconfig',
            name='max_value',
            field=models.IntegerField(default=10),
        ),
    ]
