# Generated by Django 2.0.2 on 2018-03-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180306_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SubjectConfig'),
        ),
    ]
