# Generated by Django 2.0.2 on 2018-03-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180306_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_config',
        ),
        migrations.AddField(
            model_name='subjectconfig',
            name='subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
    ]
