# Generated by Django 2.0.2 on 2018-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180306_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectconfig',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='excel_min_value',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='good_min_value',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_value',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='satis_min_value',
            field=models.IntegerField(default=4),
        ),
        migrations.DeleteModel(
            name='SubjectConfig',
        ),
    ]
